### ISSUE TITLE
Output table format

### ISSUE THREAD

**Issue by aaristov** [SRMLabHUST/QC-STORM#1]
Hi,

I've tried your tool and got the rendering with the localization table in txt format. However, encoding of this txt output is unclear, so it doesn't render correctly in the text editor. How to read your localization file? Could you provide Thunderstorm-formatted csv at the output instead? Thanks.

**Comment by SRMLabHUST** [comment]
> Hi,
> 
> I've tried your tool and got the rendering with the localization table in txt format. However, encoding of this txt output is unclear, so it doesn't render correctly in the text editor. How to read your localization file? Could you provide Thunderstorm-formatted csv at the output instead? Thanks.

Dear aaristov, the localization file is a binary txt file, in which 12 single floating point parameters are stored for each localization. We provide a Matlab file "LoadLocResult_BinaryTxt_Single_main.m" to read this file, you can find it in the matlab processing codes folder in the downloaded release version of QC-STORM.

**Comment by SRMLabHUST** [comment]
You can also try the ConvertBinLocArrayToCSV.txt by draging the binary txt file on to this exe file to convert the binary txt file into .csv file.

**Comment by SRMLabHUST** [comment]
You can also try the ConvertBinLocArrayToCSV.txt by draging the binary txt file on to this exe file to convert the binary txt file into .csv file.

**Comment by SRMLabHUST** [comment]
You can also try the ConvertBinLocArrayToCSV.exe by draging the binary txt file on to this exe file to convert the binary txt file into .csv file.
